# Generated by Django 3.2.9 on 2021-11-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250, null=True, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
    ]
