# Generated by Django 3.2.9 on 2021-11-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='image',
            field=models.ImageField(default='test', upload_to='admin/images'),
            preserve_default=False,
        ),
    ]
