# Generated by Django 3.2.9 on 2021-11-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
        ('admins', '0003_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='City.City'),
        ),
    ]
